name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: ${{ matrix.lisp }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      # Each combination of lisp and os are tested
      matrix:
        lisp: [sbcl-bin, ccl-bin]
        os: [ubuntu-latest, macOS-latest]

    steps:
     - uses: actions/checkout@v1
      - name: Install Roswell
        env:
          LISP: ${{ matrix.lisp }}
        shell: bash
        run: curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
      - name: Install Test Framework
        shell: bash
        run: ros install neil-lindquist/ci-utils
      - name: Run tests
        shell: bash
        run: ./run-tests.sh
